on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "testing GitHub actions"
      run: pwd

    - name: "print"
      run: |
        echo "Hello from GitHub Actions!"

    - uses: actions/checkout@v3

    - name: "folder contents"
      run: ls